export const lightTheme = {
    white: "#ffffff",
    body: "#ffffff",
    text: "#000000",
    cardBg: "#f8f9fa",
    cardText: "#333333",
    buttonBg: "#007bff",
    buttonText: "#ffffff",
    navbarBg: "#F5FAFF",
    logo: "#000000",
    dropdownBg: "white",
    dropdownHover: "#E8ECFC",
    dropdownTextHover: "#3859FF",
    dropdownText: "black",
    highlight: "#3859FF",
    avatarBorder: "#D9D9D9",
};

export const darkTheme = {
    white: "#ffffff",
    body: "#171717",
    text: "#ffffff",
    cardBg: "#2a2a2a",
    cardText: "#f1f1f1",
    buttonBg: "#ff9800",
    buttonText: "#000000",
    navbarBg: "#100E14",
    logo: "#ffffff",
    dropdownBg: "#0D0C0E",
    dropdownHover: "#707070",
    dropdownTextHover: "#FFFFFF",
    dropdownText: "#FFFFFF",
    highlight: "#F36F41",
    avatarBorder: "#D9D9D9",
};
